#!/bin/bash
# doh.sh — DNS-over-HTTPS with --resolve bypass (no DNS needed to test DoH)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

section "DNS-over-HTTPS (DoH :443) — with IP bypass"

log "  Using curl --resolve to bypass DNS chicken-and-egg problem"
log ""

#              Name                  Hostname                      IP                Path
test_doh       "Google"              "dns.google"                  "8.8.8.8"         "/resolve"
test_doh       "Google 2"            "dns.google"                  "8.8.4.4"         "/resolve"
test_doh       "Cloudflare"          "cloudflare-dns.com"          "104.16.248.249"  "/dns-query"
test_doh       "Cloudflare Alt"      "cloudflare-dns.com"          "104.16.249.249"  "/dns-query"
test_doh       "Cloudflare 1001"     "cloudflare-dns.com"          "1.0.0.1"         "/dns-query"
test_doh       "Quad9"               "dns.quad9.net"               "9.9.9.9"         "/dns-query"
test_doh       "Quad9 2"             "dns.quad9.net"               "149.112.112.112" "/dns-query"
test_doh       "AdGuard"             "dns.adguard-dns.com"         "94.140.14.14"    "/dns-query"
test_doh       "AdGuard 2"           "dns.adguard-dns.com"         "94.140.15.15"    "/dns-query"
test_doh       "OpenDNS"             "doh.opendns.com"             "146.112.41.2"    "/dns-query"
test_doh       "NextDNS"             "dns.nextdns.io"              "45.90.28.0"      "/dns-query"
test_doh       "NextDNS 2"           "dns.nextdns.io"              "45.90.30.0"      "/dns-query"
test_doh       "Mullvad"             "dns.mullvad.net"             "194.242.2.2"     "/dns-query"
test_doh       "CleanBrowsing"       "doh.cleanbrowsing.org"       "185.228.168.168" "/doh/security-filter"
test_doh       "Control D"           "freedns.controld.com"        "76.76.2.0"       "/p0"
test_doh       "DNS.SB"              "doh.dns.sb"                  "185.222.222.222" "/dns-query"
test_doh       "LibreDNS"            "doh.libredns.gr"             "116.202.176.26"  "/dns-query"
test_doh       "Applied Privacy"     "doh.applied-privacy.net"     "146.255.56.98"   "/query"
test_doh       "Tencent/DNSPod"      "doh.pub"                     "1.12.12.12"      "/dns-query"
test_doh       "AliDNS"              "dns.alidns.com"              "223.5.5.5"       "/dns-query"
test_doh       "TWNIC"               "dns.twnic.tw"                "101.101.101.101" "/dns-query"
test_doh       "CIRA"                "private.canadianshield.cira.ca" "149.112.121.10" "/dns-query"
test_doh       "BlahDNS (DE)"        "doh-de.blahdns.com"          "78.46.244.143"   "/dns-query"
test_doh       "BlahDNS (FI)"        "doh-fi.blahdns.com"          "95.216.212.177"  "/dns-query"
test_doh       "dnsforge.de"         "dnsforge.de"                 "176.9.93.198"    "/dns-query"
test_doh       "Digitale Ges."       "dns.digitale-gesellschaft.ch" "185.95.218.42"  "/dns-query"
test_doh       "Yandex"              "common.dot.dns.yandex.net"   "77.88.8.8"       "/dns-query"
test_doh       "DNS for Family"      "dns-doh.dnsforfamily.com"    "94.130.180.225"  "/dns-query"
test_doh       "Gcore"               "dns.gcorelabs.com"           "95.85.95.85"     "/dns-query"
