#!/bin/bash
# dot.sh — DNS-over-TLS :853
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

section "DNS-over-TLS (DoT :853)"

log "  Note: uses kdig if available, otherwise tests TLS handshake"
log ""

test_dot "Google"                    "8.8.8.8"          "dns.google"
test_dot "Google Secondary"          "8.8.4.4"          "dns.google"
test_dot "Cloudflare"                "1.1.1.1"          "cloudflare-dns.com"
test_dot "Cloudflare Secondary"      "1.0.0.1"          "cloudflare-dns.com"
test_dot "Quad9"                     "9.9.9.9"          "dns.quad9.net"
test_dot "Quad9 Secondary"           "149.112.112.112"  "dns.quad9.net"
test_dot "AdGuard"                   "94.140.14.14"     "dns.adguard-dns.com"
test_dot "AdGuard Secondary"         "94.140.15.15"     "dns.adguard-dns.com"
test_dot "OpenDNS"                   "208.67.222.222"   "dns.opendns.com"
test_dot "Mullvad"                   "194.242.2.2"      "dns.mullvad.net"
test_dot "CleanBrowsing"             "185.228.168.168"  "family-filter-dns.cleanbrowsing.org"
test_dot "DNS.SB"                    "185.222.222.222"  "dot.sb"
test_dot "UncensoredDNS"             "89.233.43.71"     "unicast.censurfridns.dk"
test_dot "LibreDNS"                  "116.202.176.26"   "dot.libredns.gr"
test_dot "Applied Privacy"           "146.255.56.98"    "dot1.applied-privacy.net"
test_dot "Digitale Gesellschaft"     "185.95.218.42"    "dns.digitale-gesellschaft.ch"
test_dot "Control D"                 "76.76.2.0"        "p0.freedns.controld.com"
test_dot "NextDNS"                   "45.90.28.0"       "dns.nextdns.io"
test_dot "Tencent/DNSPod"           "1.12.12.12"       "dot.pub"
test_dot "AliDNS"                    "223.5.5.5"        "dns.alidns.com"
test_dot "Gcore"                     "95.85.95.85"      "dns.gcorelabs.com"
test_dot "CIRA"                      "149.112.121.10"   "private.canadianshield.cira.ca"
test_dot "Yandex"                    "77.88.8.8"        "common.dot.dns.yandex.net"
test_dot "DNS for Family"            "94.130.180.225"   "dns-dot.dnsforfamily.com"
